// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOE1CSvkL0NF2365q1u5QKXAXAWelqD8',
    appId: '1:611845106940:web:1831019f7688bd2aac3b79',
    messagingSenderId: '611845106940',
    projectId: 'chat-2bd1b',
    authDomain: 'chat-2bd1b.firebaseapp.com',
    storageBucket: 'chat-2bd1b.appspot.com',
    measurementId: 'G-LTJH6R6855',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx098gmjZSug5ipVVvv_hKl5Fh2UTd8To',
    appId: '1:611845106940:android:c2a2d896e2e8e336ac3b79',
    messagingSenderId: '611845106940',
    projectId: 'chat-2bd1b',
    storageBucket: 'chat-2bd1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaOFQdFrFZkiqU0Fh0daniBIiZBAN9fE',
    appId: '1:611845106940:ios:ac27b034dd120db4ac3b79',
    messagingSenderId: '611845106940',
    projectId: 'chat-2bd1b',
    storageBucket: 'chat-2bd1b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaOFQdFrFZkiqU0Fh0daniBIiZBAN9fE',
    appId: '1:611845106940:ios:a23f341cc71a79daac3b79',
    messagingSenderId: '611845106940',
    projectId: 'chat-2bd1b',
    storageBucket: 'chat-2bd1b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
